server:
  port: 81
  servlet:
    context-path: /consumer
spring:
  application:
    name: consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: zdan
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xk.entities
